### ISSUE TITLE
bids2nda error message

### ISSUE THREAD

**Issue by neggink** [INCF/BIDS2NDA#14]
Hello,

I am getting the following error:

pni-17c02tw0zmg8wl:desktop neggink$ bids2nda ~/desktop/openneuro/conreact/ ~/desktop/openneuro/GUID_mapping ~/desktop/openneuro/conreact_NDA
Traceback (most recent call last):
  File "/Users/neggink/anaconda/bin/bids2nda", line 11, in <module>
    load_entry_point('BIDS2NDA==0.1.0', 'console_scripts', 'bids2nda')()
  File "/Users/neggink/anaconda/lib/python3.6/site-packages/bids2nda/main.py", line 316, in main
    run(args)
  File "/Users/neggink/anaconda/lib/python3.6/site-packages/bids2nda/main.py", line 207, in run
    image_unit4 = units_dict[nii.header.get_xyzt_units()[1]]
KeyError: 'unknown'

Thanks,
Neggin

**Comment by chrisfilo** [comment]
Does your input dataset pass the validator?
https://github.com/INCF/bids-validator

**Comment by neggink** [comment]
Yes, it did

**Comment by chrisfilo** [comment]
It seem that you have 4D files in your dataset that do not have the units for the fourth dimension defined. This is unexpected. Usually only _bold files are 4D and should define (in the nifti header) what is the unit of the 4th dimension (seconds or milliseconds).

**Comment by leej3** [comment]
I have come across this problem too. I think it can be avoided by using dcm2niix for conversion from dicom to nifti. If that is not possible you'll have to modify the nifti header. The xyzt_units encodes both spatial and time dimensions as described here: https://brainder.org/2012/09/23/the-nifti-file-format/

So for a scan using mm (2) and seconds (8) the xyzt would be 2 +8 =10

In python:
```
import nibabel as nb
nii_path = 'path_to_scan'
img = nb.load(nii_path)
 img.header['xyzt_units'] = 10
img.to_filename(nii_path)
```

If something so fundamental is broken in the nifti you should strongly consider converting to nifti with dcm2niix though. If that doesn't solve the issue it should be fixed there.

**Comment by neggink** [comment]
Hello,
Thank you for all your help, that error was fixed but now I am getting this one:

Traceback (most recent call last):
  File "/Users/neggink/anaconda/bin/bids2nda", line 11, in <module>
    load_entry_point('BIDS2NDA==0.1.0', 'console_scripts', 'bids2nda')()
  File "/Users/neggink/anaconda/lib/python3.6/site-packages/bids2nda/main.py", line 316, in main
    run(args)
  File "/Users/neggink/anaconda/lib/python3.6/site-packages/bids2nda/main.py", line 159, in run
    dict_append(image03_dict, 'scan_type', suffix_to_scan_type[suffix])
KeyError: 'FLASH'

**Comment by neggink** [comment]
The NDA has added FLASH files to the 'scan_type' column of their Image03 specification: (https://ndar.nih.gov/data_structure.html?short_name=image03) as "MR structural (FLASH)". Can the converter be modified to include this?

Thanks!

**Comment by chrisfilo** [comment]
I don't have time to perform this modification myself, but if you send a pull request I would be happy to merge it

**Comment by leej3** [comment]
I can help if you want @neggink . I've done that before

**Comment by neggink** [comment]
That would be great @leej3 ! Thank you!!

**Comment by leej3** [comment]
Ok I've edited the code. so in an environment that doesn't already contains bids2nda install my code:
```
git clone https://github.com/leej3/BIDS2NDA.git
cd BIDS2NDA
git checkout add_flash_scantype
pip install -e .
```

Then try running it on your data and report back. If it works I'll submit it as a pull request.

**Comment by neggink** [comment]
It works! Thank you

**Comment by leej3** [comment]
Great. Happy uploading.

**Comment by ebarrick** [comment]
Hello,

I'm getting the following error:

  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/anaconda2/bin/bids2nda", line 11, in <module>
    sys.exit(main())
  File "/anaconda2/lib/python2.7/site-packages/bids2nda/main.py", line 317, in main
    run(args)
  File "/anaconda2/lib/python2.7/site-packages/bids2nda/main.py", line 154, in run
    description = suffix + " " + metadata["TaskName"]
KeyError: 'TaskName'

But I'm unsure why this error is occurring.

Thanks!
E
