### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by anukriti-singh** [INCF/BIDS2NDA#15]
I am making a wetherbot. This is the error popped up when running the nlu_model1.py file.Please help me out.

$ python nlu_model1.py
Traceback (most recent call last):
  File "nlu_model1.py", line 12, in <module>
    train_nlu('./data/data.json', 'config.yml', './models/nlu')
  File "nlu_model1.py", line 7, in train_nlu
    trainer = Trainer(RasaNLUModelConfig(config))
  File "C:\Users\Anu\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_nlu\config.py", line 79, in __init__
    self.override(configuration_values)
  File "C:\Users\Anu\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_nlu\config.py", line 160, in override
    self.__dict__.update(config)
ValueError: dictionary update sequence element #0 has length 1; 2 is required

**Comment by chrisfilo** [comment]
Wrong repo?
