### ISSUE TITLE
ValueError: dictionary update sequence element #0 has length 1; 2 is required

### ISSUE THREAD

**Issue by chrisfilo** [INCF/BIDS2NDA#7]
> I am attempting to submit my data to the NDA. The dataset passed the bids-validator but I am having trouble with the bids2nda tool. I get the following error:
> 
> 
> 
> ValueError: dictionary update sequence element #0 has length 1; 2 is required
> 
> 
> 
> I'm not sure where to start with this
https://groups.google.com/d/msgid/bids-discussion/827d0371-8db9-47b0-9add-abfddfa06090%40googlegroups.com?utm_medium=email&utm_source=footer

```
neggink$ bids2nda CommunicationCircle_Sherlock_Merlin /Users/neggink/Documents/guid_mapping.txt NDA

Traceback (most recent call last):

  File "/Users/neggink/anaconda/bin/bids2nda", line 11, in <module>

    load_entry_point('BIDS2NDA==0.1.0', 'console_scripts', 'bids2nda')()

  File "/Users/neggink/anaconda/lib/python3.6/site-packages/bids2nda/main.py", line 316, in main

    run(args)

  File "/Users/neggink/anaconda/lib/python3.6/site-packages/bids2nda/main.py", line 79, in run

    guid_mapping = dict([line.split(" - ") for line in open(args.guid_mapping).read().split("\n") if line != ''])

ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

**Comment by chrisfilo** [comment]
I expect there is something wrong with your guid_mapping file. Is it following this format? https://github.com/INCF/BIDS2NDA#guid_mapping-file-format

**Comment by neggink** [comment]
Hello,
Attached is my guid_mapping file
[guid_mapping.txt](https://github.com/INCF/BIDS2NDA/files/1356660/guid_mapping.txt)

**Comment by chrisfilo** [comment]
It's missing `-` separating the IDs. See https://github.com/INCF/BIDS2NDA#guid_mapping-file-format

For example
```
sub-01 - FOOGIUD384383
sub-02 - FOOGIUD383383
sub-03 - FOOGIUD384363
```

Also no header.

**Comment by neggink** [comment]
I will change that. Thank you!!

**Comment by neggink** [comment]
I recieved a different error when I reran bids2nda:

neggink$ bids2nda CommunicationCircle_Sherlock_Merlin /Users/neggink/Documents/guid_mapping.txt NDA
Traceback (most recent call last):
  File "/Users/neggink/anaconda/bin/bids2nda", line 11, in <module>
    load_entry_point('BIDS2NDA==0.1.0', 'console_scripts', 'bids2nda')()
  File "/Users/neggink/anaconda/lib/python3.6/site-packages/bids2nda/main.py", line 316, in main
    run(args)
  File "/Users/neggink/anaconda/lib/python3.6/site-packages/bids2nda/main.py", line 110, in run
    participants_df = pd.read_csv(os.path.join(args.bids_directory, "participants.tsv"), header=0, sep="\t")
  File "/Users/neggink/anaconda/lib/python3.6/site-packages/pandas/io/parsers.py", line 655, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/Users/neggink/anaconda/lib/python3.6/site-packages/pandas/io/parsers.py", line 405, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/neggink/anaconda/lib/python3.6/site-packages/pandas/io/parsers.py", line 762, in __init__
    self._make_engine(self.engine)
  File "/Users/neggink/anaconda/lib/python3.6/site-packages/pandas/io/parsers.py", line 966, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/Users/neggink/anaconda/lib/python3.6/site-packages/pandas/io/parsers.py", line 1582, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 394, in pandas._libs.parsers.TextReader.__cinit__ (pandas/_libs/parsers.c:4209)
  File "pandas/_libs/parsers.pyx", line 710, in pandas._libs.parsers.TextReader._setup_parser_source (pandas/_libs/parsers.c:8873)
FileNotFoundError: File b'CommunicationCircle_Sherlock_Merlin/participants.tsv' does not exist


When I ran the bids_validator I did not get an error for the participants.tsv and it is in the correct directory

**Comment by chrisfilo** [comment]
Maybe you are in a wrong directory? Try providing an absolute path to your BIDS dataset.

**Comment by neggink** [comment]
That worked but now I get another error for the guid_mapping:
Traceback (most recent call last):
  File "/Users/neggink/anaconda/bin/bids2nda", line 11, in <module>
    load_entry_point('BIDS2NDA==0.1.0', 'console_scripts', 'bids2nda')()
  File "/Users/neggink/anaconda/lib/python3.6/site-packages/bids2nda/main.py", line 316, in main
    run(args)
  File "/Users/neggink/anaconda/lib/python3.6/site-packages/bids2nda/main.py", line 119, in run
    dict_append(image03_dict, 'subjectkey', guid_mapping[bids_subject_id])
KeyError: '01'

Also, thank you so much for helping!!!

**Comment by chrisfilo** [comment]
hmm - try removing `sub-` form the guid mapping file?

**Comment by neggink** [comment]
That worked! And another error popped up:

Traceback (most recent call last):
  File "/Users/neggink/anaconda/bin/bids2nda", line 11, in <module>
    load_entry_point('BIDS2NDA==0.1.0', 'console_scripts', 'bids2nda')()
  File "/Users/neggink/anaconda/lib/python3.6/site-packages/bids2nda/main.py", line 316, in main
    run(args)
  File "/Users/neggink/anaconda/lib/python3.6/site-packages/bids2nda/main.py", line 130, in run
    scans_df = pd.read_csv(scans_file, header=0, sep="\t")
  File "/Users/neggink/anaconda/lib/python3.6/site-packages/pandas/io/parsers.py", line 655, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/Users/neggink/anaconda/lib/python3.6/site-packages/pandas/io/parsers.py", line 411, in _read
    data = parser.read(nrows)
  File "/Users/neggink/anaconda/lib/python3.6/site-packages/pandas/io/parsers.py", line 982, in read
    ret = self._engine.read(nrows)
  File "/Users/neggink/anaconda/lib/python3.6/site-packages/pandas/io/parsers.py", line 1719, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 890, in pandas._libs.parsers.TextReader.read (pandas/_libs/parsers.c:10862)
  File "pandas/_libs/parsers.pyx", line 912, in pandas._libs.parsers.TextReader._read_low_memory (pandas/_libs/parsers.c:11138)
  File "pandas/_libs/parsers.pyx", line 966, in pandas._libs.parsers.TextReader._read_rows (pandas/_libs/parsers.c:11884)
  File "pandas/_libs/parsers.pyx", line 953, in pandas._libs.parsers.TextReader._tokenize_rows (pandas/_libs/parsers.c:11755)
  File "pandas/_libs/parsers.pyx", line 2184, in pandas._libs.parsers.raise_parser_error (pandas/_libs/parsers.c:28765)
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 3, saw 2

**Comment by neggink** [comment]
That worked! And another error popped up:

Traceback (most recent call last):
  File "/Users/neggink/anaconda/bin/bids2nda", line 11, in <module>
    load_entry_point('BIDS2NDA==0.1.0', 'console_scripts', 'bids2nda')()
  File "/Users/neggink/anaconda/lib/python3.6/site-packages/bids2nda/main.py", line 316, in main
    run(args)
  File "/Users/neggink/anaconda/lib/python3.6/site-packages/bids2nda/main.py", line 139, in run
    sdate = date.split("-")
UnboundLocalError: local variable 'date' referenced before assignment

**Comment by chrisfilo** [comment]
There is probably something wrong with your scans.tsv file. Please consult the BIDS specification http://bids.neuroimaging.io/bids_spec1.0.2.pdf

**Comment by neggink** [comment]
Hello,
I have successfully uploaded my dataset to the NDA, thank you for all your help!!!

**Comment by chrisfilo** [comment]
Fantastic!

**Comment by Coulborn** [comment]
Hi, I have come across a similar error also. The scans.tsv file appears to be correct (see below) @neggink Do you remember how you solved your issue? 
filename	acq_time
func/sub-DMF1507_ses-02_task-reward_bold.nii.gz	2022-06-25T13:15:20

error:
(base) seancoulborn@fixed-169-229-236-3 ~ % bids2nda /Users/seancoulborn/Documents/NDA_upload /Users/seancoulborn/Documents/GUID_MAPPING.txt /Users/seancoulborn/Documents/NDA_ready
Traceback (most recent call last):
  File "/opt/anaconda3/bin/bids2nda", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.8/site-packages/bids2nda/main.py", line 419, in main
    run(args)
  File "/opt/anaconda3/lib/python3.8/site-packages/bids2nda/main.py", line 192, in run
    sdate = date.split("-")
UnboundLocalError: local variable 'date' referenced before assignment
